### ISSUE TITLE
[S1] Implementar mecanismo de login com facebook

### ISSUE THREAD

**Issue by wendellpbarreto** [wendellpbarreto/dolly#4]

**Comment by rafaelfqueiroz** [comment]
@Maychell Preciso que essa issue seja resolvida logo, pois é o passo inicial para o projeto. Existem duas outras issues que dependem desta.

**Comment by Maychell** [comment]
@rafaelfqueiroz Criei um pull request solucionando a issue. Por favor, analisar e se precisar de alteracoes, avise que farei o mais rapido possivel.
